version: '3.8'

services:
  redis:
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis/
      - ./redis.conf:/etc/redis/redis.conf
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  redis-data:

networks:
  defaulf:
    driver: bridge
