version: '3.8'

services:
  redis:
    image: redis:5
    volumes:
      - redis-data:/var/lib/redis/
      - redis.conf:/redis/redis.conf
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  redis-data: